
version: '3'
services:
  file-share:
    build: .
    ports:
      - "${SHARE_DOWNLOAD_PORT}:80"
      - "${SHARE_UPLOAD_PORT}:22"
    volumes:
      - "${SHARE_STORAGE}:/file-share/storage"
    stop_signal: SIGINT